name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: auto-release-${{ github.ref }}

jobs:
  release:
    name: Release
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-build-release.yml@v0.16.0
    with:
      PRODUCTION_RELEASE: true
      BUILD_ENABLED: false
    secrets:
      CHECKOUT_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
      NPM_TOKEN: ${{ secrets.FORGE_NPM_TOKEN }}
 
