name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: auto-release-${{ github.ref }}

jobs:
  release:
    name: Release
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-build-release.yml@v0.10.0
    with:
      PRODUCTION_RELEASE: true
      BUILD_ENABLED: false
    secrets:
      GITHUB_APP_ID: ${{ secrets.TCP_AUTOMATION_APP_ID }}
      GITHUB_APP_KEY: ${{ secrets.TCP_AUTOMATION_APP_KEY }}
      ARTIFACTORY_TOKEN: ${{ secrets.FORGE_ARTIFACTORY_TOKEN }}
      ARTIFACTORY_USERNAME: ${{ secrets.FORGE_ARTIFACTORY_USERNAME }}
      ARTIFACTORY_REGISTRY: ${{ secrets.FORGE_ARTIFACTORY_NPM_REGISTRY }}
