name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: auto-release-${{ github.ref }}
permissions:
  contents: write

jobs:
  release:
    name: Release
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-build-release.yml@v0.13.1
    with:
      PRODUCTION_RELEASE: true
      BUILD_ENABLED: false
    secrets:
      NPM_TOKEN: ${{ secrets.FORGE_NPM_TOKEN }}
