name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: auto-release-${{ github.ref }}

jobs:
  release:
    name: Release
    uses: tyler-technologies-oss/forge-automation-shared/.github/workflows/wf-build-release.yml@v1.0.0
    with:
      PRODUCTION_RELEASE: true
      BUILD_ENABLED: false
    secrets:
      GITHUB_APP_ID: ${{ secrets.FORGE_AUTOBOT_ID }}
      GITHUB_APP_KEY: ${{ secrets.FORGE_AUTOBOT_SECRET }}
      NPM_TOKEN: ${{ secrets.FORGE_NPM_TOKEN }}
 
